agregué el modal a promociones bancarias y corregí el componente busc…
Yanina-Unrein/MyVet_TSDWAD pull request #253
Opened 2023-05-18 17:36 UTC by santipeironi

- agregué el modal a promociones bancarias
 - corregí el componente buscar-animales según indicaciones de Yanina, que proporcionó el código faltante
 - además dejé en standby el componente formulario-envío, para ser reubicado y utilizado posteriormente.

2023-05-18 21:29 UTC, Yanina-Unrein requested changes
el estilo mándalo al archivo .css porque ahí no va, porque no es la estructura del html así acá, aca arrancamos desde body y esa etiqueta  <style> va por arriba de body y nuevamente no es buena práctica, siempre conviene poner los estilos en un archivo css.
El resto parece estar bien y estas apuntando a Develop

2023-05-18 21:30 UTC, Yanina-Unrein commented on Frontend/myvet.app/src/app/ecommerce/promociones-bancarias/promociones-bancarias.component.html
> +<style>
esto va en el archivo css!

2023-05-18 23:24 UTC, Yanina-Unrein approved these changes

2023-05-18 23:49 UTC, Yanina-Unrein requested changes
tenes que cambiar eso que señale santi y fijarte que se ve bien el resposive

2023-05-21 15:37 UTC, Yanina-Unrein approved these changes

2023-05-21 15:58 UTC, santipeironi commented
"dale que va"

2023-05-21 20:52 UTC, merged