Creé componente menú y servicio registro según las TKs
Yanina-Unrein/MyVet_TSDWAD pull request #289
Opened 2023-06-04 00:00 UTC by santipeironi

Se realizaron las tareas según se detallan a continuación:

#TK91 - Crear el componente menú de usuario. #281 

#TK88 - Crear servicio para implementar método POST para registro. (Submit del formulario) #280

2023-06-04 23:46 UTC, HernanRT approved these changes
Parece estar todo ok.

2023-06-05 00:22 UTC, Loreaylen requested changes
Tenés errores de compilación porque cuando trajiste cambios que tenían conflictos no los resolviste y quedaron todos los marcadores. Fijate bien qué es lo que tiene que quedar y corregilo.

2023-06-05 00:22 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/ecommerce.module.ts
> +<<<<<<< HEAD
Tenés puestos los marcadores que te pone Visual cuando tenés conflictos de merge. Quedaron porque no los resolviste, tenés que sacarlos. Podés hacerlo manualmente o desde el visual.

2023-06-05 00:22 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +<<<<<<< HEAD
Tenés puestos los marcadores que te pone visual cuando tenés conflictos. Resolvelos manualmente o desde el visual.

2023-06-05 00:22 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/catalogo/catalogo.component.html
> +<<<<<<< HEAD
Sacá los marcadores. Desde el visual o manualmente, pero no pueden quedar ahí.

2023-06-05 01:45 UTC, Loreaylen requested changes
Está bien resuelto el conflicto del componente catálogo, resolvé los otros dos que quedaron.

2023-06-05 02:22 UTC, santipeironi reviewed
revisé los comentarios que faltaban y corregí

2023-06-05 02:32 UTC, Loreaylen requested changes

2023-06-05 02:32 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
Sacar items repetidos

2023-06-05 02:32 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/ecommerce.module.ts
El componente ListaDeDeseosComponent está importado 2 veces.

2023-06-07 02:37 UTC, santipeironi commented
corregí el catálogo para mergear

2023-06-07 03:07 UTC, closed without merging