Dev santiago2023
Yanina-Unrein/MyVet_TSDWAD pull request #300
Opened 2023-06-07 03:14 UTC by santipeironi

Luego de solucionar los conflictos del PR anterior, actualicé mi repositorio correctamente para pasar el nuevo PR en limpio y corriendo en servidor.

2023-06-07 13:55 UTC, Loreaylen requested changes
Todo bárbaro, compila bien. Lo único que hace falta es que encierres el ul del navbar en un div como te indiqué en otro comentario, porque sino cuando llegue al breakpoint se va a romper. 

Ese div permite que se convierta en un menú desplegable cuando se achique la pantalla.

Corregís eso y ya estarías 👍🏼

2023-06-07 13:55 UTC, Loreaylen commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
Encerrá el ul dentro de un div con las clases "collapse navbar-collapse" y con id "navbarNav"

2023-06-09 00:11 UTC, santipeironi commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
listo, le agregé un div para contener el ul

2023-06-09 01:19 UTC, Yanina-Unrein commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
santi al div , agregale esto si no lo tiene <div class="collapse navbar-collapse" id="navbarNav">

2023-06-09 01:19 UTC, Yanina-Unrein commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
div class="collapse navbar-collapse" id="navbarNav"   lo de la clase y el id

2023-06-09 01:20 UTC, Yanina-Unrein commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
` <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">Alimentos</li>
        <li class="nav-item">Juguetes</li>
        <li class="nav-item">Camas</li>
        <li class="nav-item">indumentaria</li>
        <li class="nav-item">Accesorios</li>
        <li class="nav-item">Higiene y belleza</li>
        <li class="nav-item">Salud</li>
        <li class="nav-item">Casas</li>
        <li class="nav-item">Cuchas</li>
        <li class="nav-item">Bebederos</li>
        <li class="nav-item">Comederos</li>
        <li class="nav-item">Peceras</li>
        <li class="nav-item">Acuarios</li>
      </ul>
    </div>
`

2023-06-09 01:21 UTC, Yanina-Unrein commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
`
     <div class="collapse navbar-collapse" id="navbarNav">
`

2023-06-09 23:25 UTC, santipeironi commented on Frontend/myvet.app/src/app/ecommerce/categorias/categorias.component.html
> +    <ul class="navbar-nav">
está en la linea 6, avise, estoy atenti cualquier cosilla

2023-06-10 23:35 UTC, Loreaylen approved these changes
Está bastante bien, ya estaría para aprobar.

2023-06-10 23:38 UTC, merged